Accessing/Changing specific elements, rows, columns, etc

In [3]:
import numpy as np

In [4]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [r, c]
a[1,-2]

13

In [12]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [14]:
# Getting a little more fancy [starindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [15]:
# Change something
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
# Replace
a[:, 1] = [1,2]
print(a)

[[ 1  1  1  4  5  6  7]
 [ 8  2  2 11 12 20 14]]


In [19]:
# *3-d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
# Get specific element (work outside in)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [25]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
