In [2]:
import numpy as np

In [3]:
# All 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [4]:
# All 1s matrix
np.ones((4,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [5]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [6]:
# Any other number (full_like)
np.full_like((2,3), 4)

array([4, 4])

In [7]:
# Random decimal number
np.random.rand(4,2)

array([[0.50182523, 0.73186271],
       [0.94318639, 0.8409131 ],
       [0.12697916, 0.59609077],
       [0.26270203, 0.83616602]])

In [36]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-2,  2,  5],
       [-4,  0,  0],
       [ 0,  6, -1]])

In [41]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
# Repeat an array
arr= np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [69]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [71]:
#### Copying arrays

In [78]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]
