In [1]:
import numpy as np

In [16]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[9,8,7],[6,5,4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [7]:
# Get Dimension
b.ndim
a.ndim

1

In [8]:
# Get Shape
b.shape

(2, 3)

In [17]:
# Get Type
a.dtype

dtype('int32')

In [21]:
# Get Size
a.itemsize
b.itemsize

8

In [19]:
# Get total size
a.nbytes

12