Linear Algebra

In [3]:
import numpy as np

In [11]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [15]:
# Find the deteminant
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [18]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.min(stats, axis=0)

array([1, 2, 3])

In [22]:
np.max(stats)

6

In [24]:
np.sum(stats, axis=0)

array([5, 7, 9])