In [1]:
import numpy as np

In [10]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
a + 2

array([3, 4, 5, 6])

In [6]:
a - 2 

array([-1,  0,  1,  2])

In [7]:
a * 2

array([2, 4, 6, 8])

In [11]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [12]:
a ** 2

array([ 1,  4,  9, 16])

In [18]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])