#### Miscellaneous

Load Data from File

In [2]:
import numpy as np

In [18]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')

In [19]:
# Advanced indexing and Boolean Masking

In [22]:
filedata[filedata > 80]

array([664, 213, 325, 657,  85, 577,  86], dtype=int32)

In [25]:
# You can index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [32]:
np.any(filedata > 90, axis=1)

array([ True,  True,  True])

In [37]:
# The ~ means not
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False, False, False, False, False,  True, False,  True,
         True, False,  True, False,  True,  True,  True, False]])